output: .

collections:
  - common
  - typescript

excludes:
  - .cspell.json
  - .eslintrc.json
  - package.json
  - Gruntfile.js

render_context:
  name: infer-version
  description: Infer a project's version from its configuration files.
  version: 0.2.0
  author: joellefkowitz
  codacy_id: cb2202d9612c4d5580024f4786a53723
  keywords:
    - version
