severity: low
exclude:
  - message: Codacy project public id
    pattern: cb2202d9612c4d5580024f4786a53723

  - message: Codacy project public id (old)
    pattern: 0bf54bb20a744bec9c3d36ac206a0f3d

  - message: Sourcemaps
    pattern: sourceMappingURL=data:application/json;base64,

  - message: Giphy links
    pattern: https://media.giphy.com/media/

  - message: Dependencies
    paths:
      - package-lock.json
      - node_modules
      - venv
      - yarn-error.log
      - yarn.lock
